#!/bin/bash
clear
URL=$1
DLDIR=/data/data/com.termux/files/home/storage/downloads/yt-dlp2

echo "downloading ur video..."
echo ""
[ ! -d "$DLDIR" ] && mkdir -pv "$DLDIR"
yt-dlp --extractor-args "youtube:player_client=android" "$URL" -c -o "$DLDIR/%(title)s [%(id)s].%(ext)s" -R infinite --retry-sleep 3

# shfmt -w /storage/emulated/0/termux-url-opener
# cat /storage/emulated/0/termux-url-opener >$HOME/bin/termux-url-opener
